"global.anthropic.claude-opus-4-6-v1":
    api_type: "openai"
    base_url: "https://ai-gateway-internal.dp.tech/v1"
    api_key: "sk-Zj3a7RQDVCXr-Axg-0gtkg"
    temperature: 0.2

"zhangli/claude-4.6-opus":
    api_type: "openai"
    base_url: "https://ai-gateway-internal.dp.tech/v1"
    api_key: "sk-Zj3a7RQDVCXr-Axg-0gtkg"
    temperature: 0.2

"cds/Claude-4.6-opus":
    api_type: "openai"
    base_url: "https://ai-gateway-internal.dp.tech/v1"
    api_key: "sk-Zj3a7RQDVCXr-Axg-0gtkg"
    temperature: 0.2

"gemini-3.1-pro-preview":
    api_type: "openai"
    base_url: "https://ai-gateway-internal.dp.tech/v1"
    api_key: "sk-Zj3a7RQDVCXr-Axg-0gtkg"
    temperature: 0.2

"gemini-3-pro-preview":
    api_type: "openai"
    base_url: "https://ai-gateway-internal.dp.tech/v1"
    api_key: "sk-Zj3a7RQDVCXr-Axg-0gtkg"
    temperature: 0.2