"""
Dual-energy CT forward model.

Provides:
- X-ray spectra for low-energy and high-energy measurements
- Polychromatic forward projection model
- Radon transform wrappers

Note: Mass attenuation coefficients (NIST XCOM data) are stored in
raw_data.npz as instrument calibration data, not hardcoded here.
They are generated by generate_data.py during data creation.
"""

import numpy as np
from skimage.transform import radon, iradon


def get_spectra(energies):
    """Generate simplified X-ray spectra for dual-energy CT.

    Low-energy spectrum: models an 80 kVp tube (Gaussian peak ~55 keV).
    High-energy spectrum: models a 140 kVp tube (Gaussian peak ~90 keV).

    Parameters
    ----------
    energies : ndarray, shape (nE,)
        Energy grid in keV.

    Returns
    -------
    spectra : ndarray, shape (2, nE)
        spectra[0] = low-energy photon fluence (photons per energy bin).
        spectra[1] = high-energy photon fluence.
    """
    # Low energy: 80 kVp, peak around 55 keV
    low = np.exp(-0.5 * ((energies - 55.0) / 12.0) ** 2)
    low[energies > 80] = 0.0
    low[energies < 20] = 0.0
    # Normalise to total of ~1e6 photons per detector bin
    low = low / low.sum() * 1.0e6

    # High energy: 140 kVp, peak around 90 keV
    high = np.exp(-0.5 * ((energies - 90.0) / 20.0) ** 2)
    high[energies > 140] = 0.0
    high[energies < 20] = 0.0
    high = high / high.sum() * 1.5e6  # higher fluence for high-energy scan

    return np.stack([low, high], axis=0)


def radon_transform(image, theta):
    """Compute the Radon transform (line integrals) of a 2D image.

    Parameters
    ----------
    image : ndarray, shape (N, N)
        2D image (material density map in g/cm^3, or similar).
    theta : ndarray, shape (nAngles,)
        Projection angles in degrees.

    Returns
    -------
    sinogram : ndarray, shape (nBins, nAngles)
        Line integrals. nBins is determined by scikit-image (typically N
        or the diagonal length, but for an NxN image it is close to N).
    """
    return radon(image, theta=theta, circle=True)


def fbp_reconstruct(sinogram, theta, output_size=None, filter_name="ramp"):
    """Filtered back-projection reconstruction.

    Parameters
    ----------
    sinogram : ndarray, shape (nBins, nAngles)
        Sinogram (material density line integrals or standard attenuation).
    theta : ndarray, shape (nAngles,)
        Projection angles in degrees.
    output_size : int or None
        Reconstructed image size. If None, determined automatically.
    filter_name : str
        FBP filter (default 'ramp').

    Returns
    -------
    image : ndarray, shape (output_size, output_size)
        Reconstructed image.
    """
    return iradon(sinogram, theta=theta, output_size=output_size,
                  filter_name=filter_name, circle=True)


def polychromatic_forward(material_sinograms, spectra, mus, dE=1.0):
    """Compute expected photon counts from material line-integral sinograms.

    Implements the polychromatic Beer-Lambert law:
        g_m = sum_E I_{0,m}(E) * exp(-sum_k a_k * mu_k(E)) * dE

    Parameters
    ----------
    material_sinograms : ndarray, shape (nMats, nBins, nAngles)
        Line integrals for each basis material (g/cm^2 path length).
    spectra : ndarray, shape (nMeas, nE)
        Incident photon spectra for each measurement.
    mus : ndarray, shape (nMats, nE)
        Mass attenuation coefficients.
    dE : float
        Energy bin width in keV (default 1.0).

    Returns
    -------
    counts : ndarray, shape (nMeas, nBins, nAngles)
        Expected photon counts per detector bin per view.
    """
    nMats, nBins, nAngles = material_sinograms.shape
    nMeas, nE = spectra.shape

    # Total linear attenuation path: sum_k a_k * mu_k(E)
    # material_sinograms: (nMats, nBins, nAngles) -> (nMats, nBins, nAngles, 1)
    # mus: (nMats, nE) -> (nMats, 1, 1, nE)
    atten_arg = np.einsum("mba,me->bae", material_sinograms, mus)
    # atten_arg: (nBins, nAngles, nE)

    transmitted = np.exp(-atten_arg)  # (nBins, nAngles, nE)

    # spectra: (nMeas, nE)
    # counts_m = sum_E I0_m(E) * transmitted(E) * dE
    counts = np.einsum("se,bae->sba", spectra * dE, transmitted)
    # counts: (nMeas, nBins, nAngles)

    return counts
