"""
Data loading and preprocessing for dynamic black hole imaging.

Loads the per-frame observation data generated by generate_data.py
and prepares it for the StarWarps solver.
"""

import os
import json
import numpy as np

from src.physics_model import DFTForwardModel


def load_observation(data_dir):
    """Load per-frame observation data from raw_data.npz.

    Args:
        data_dir: path to data/ directory

    Returns:
        dict with:
            'n_frames': int
            'frame_times': (n_frames,) array in hours
            'vis': list of (M_t,) complex arrays
            'sigma': list of (M_t,) arrays
            'uv': list of (M_t, 2) arrays
            'station_ids': list of (M_t, 2) int arrays
    """
    data = np.load(os.path.join(data_dir, 'raw_data.npz'))
    n_frames = int(data['n_frames'])

    obs = {
        'n_frames': n_frames,
        'frame_times': data['frame_times'],
        'vis': [],
        'sigma': [],
        'uv': [],
        'station_ids': [],
    }

    for t in range(n_frames):
        obs['vis'].append(data[f'vis_{t}'])
        obs['sigma'].append(data[f'sigma_{t}'])
        obs['uv'].append(data[f'uv_{t}'])
        obs['station_ids'].append(data[f'station_ids_{t}'])

    return obs


def load_metadata(data_dir):
    """Load imaging metadata from meta_data JSON file.

    Args:
        data_dir: path to data/ directory

    Returns:
        dict with keys: N, pixel_size_rad, n_frames, total_flux, etc.
    """
    with open(os.path.join(data_dir, 'meta_data'), 'r') as f:
        return json.load(f)


def load_ground_truth(task_dir):
    """Load ground-truth video from evaluation/reference_outputs/.

    Args:
        task_dir: root task directory

    Returns:
        (n_frames, N, N) ndarray
    """
    gt_path = os.path.join(task_dir, 'evaluation', 'reference_outputs',
                           'ground_truth.npy')
    return np.load(gt_path)


def build_per_frame_models(obs, meta):
    """Build a DFTForwardModel for each frame.

    Args:
        obs: observation dict from load_observation()
        meta: metadata dict from load_metadata()

    Returns:
        list of DFTForwardModel instances
    """
    N = meta['N']
    psize = meta['pixel_size_rad']
    models = []
    for t in range(obs['n_frames']):
        models.append(DFTForwardModel(obs['uv'][t], N, psize))
    return models


def prepare_data(data_dir, task_dir=None):
    """Load all data needed for reconstruction.

    Args:
        data_dir: path to data/ directory
        task_dir: root task directory (defaults to parent of data_dir)

    Returns:
        (obs, meta, gt): observation dict, metadata dict, ground truth array
    """
    if task_dir is None:
        task_dir = os.path.dirname(data_dir)

    obs = load_observation(data_dir)
    meta = load_metadata(data_dir)
    gt = load_ground_truth(task_dir)

    return obs, meta, gt
